export { mountDeck } from './core/mount.js';
export { Deck, useDeckMeta, SLIDE_WIDTH, SLIDE_HEIGHT, type DeckProps, type DeckMeta, type Transition } from './core/Deck.js';
export { Slide, type SlideProps } from './core/Slide.js';
export { Step, useStep, useStepValue, useSteps, type StepProps, type StepState } from './core/steps.js';
export { Interactive, type InteractiveProps } from './interactive/Interactive.js';
export { useTimeline, type Keyframe, type TimelineOptions } from './interactive/timeline.js';
export { Replay, type ReplayProps } from './interactive/Replay.js';
export { usePointerOn, useSlideIndex, type PointerOnSlide } from './interactive/runtime.js';
export { replay, trace, type Source } from './interactive/sources.js';
export type { StillReason } from './interactive/environment.js';
export { TitleSlide, type TitleSlideProps } from './core/TitleSlide.js';
export { StandoutSlide, type StandoutSlideProps } from './core/StandoutSlide.js';
export type { Notes } from './core/SpeakerNotes.js';
export { Columns, type ColumnsProps } from './layout/Columns.js';
export { Figure, type FigureProps } from './layout/Figure.js';
export { Stack, type StackProps, type StackGap } from './layout/Stack.js';
export { Section, type SectionProps } from './layout/Section.js';
export { Screenshot, type ScreenshotProps, type Crop } from './layout/Screenshot.js';
export { MonoBlock, type MonoBlockProps } from './layout/MonoBlock.js';
export { Text, type TextProps } from './layout/Text.js';
export type { ImageAsset } from './assets.js';
export { Cite, References, type CiteProps, type ReferencesProps } from './cite/Cite.js';
export { ReferencesSlide, type ReferencesSlideProps } from './cite/ReferencesSlide.js';
export type { BibEntry, Bibliography } from './cite/types.js';
